# Training Loop 

1. What is training?
2. What is a training loop?
3. Forward pass
4. Prediction
5. Calculate loss
6. Gradients
7. Backpropagation
8. Optimizer
9. optimizer.zero_grad()
10. optimizer.step()
11. Epoch
12. Complete training loop
13. Observe loss decreasing

## 1. What is training

Training means repeatedly adjusting the model's parameters so that its predictions become closer to the actual values.

We have a model:

Input → Model → Prediction

Initially, the model doesn't know the correct relationship.

For example:

Input       Actual
  1           20
  2           40
  3           60
  4           80

Our model starts with random parameters.

For example:

weight = 0.4
bias = 0.8

For input 2:

$$ prediction = weight \times x + bias $$ $$ = 0.4(2)+0.8 $$ $$ = 1.6 $$

But the actual answer is:

40

## 2. What is training loop

Instead of training only once:

Input
 ↓
Model
 ↓
Prediction

we repeatedly do:

Input
 ↓
Model
 ↓
Prediction
 ↓
Loss
 ↓
Improve model
 ↓
Repeat

That's the training loop.

## Forward pass

In [17]:
# import the libraries

import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch import nn as nn


# create the dataset 

class MyDataset(Dataset):

    # initlize the dataset

    def __init__(self):

        #input
        
        self.x = torch.tensor(
            [
                [1.0],
                [2.0],
                [3.0],
                [4.0]
            ]
        )

        #output

        self.y = torch.tensor(
            [
                [20.0],
                [40.0],
                [60.0],
                [80.0]
            ]
        )

    # len 

    def __len__(self):

        return len(self.x)

    # get the sample

    def __getitem__(self,index):

        return self.x[index],self.y[index]


# Dataset object

dataset = MyDataset()

# DataLoader 

loader = DataLoader(
        
        dataset,
        batch_size =2,
        shuffle = False
)


#Model

model = nn.Linear(

    in_features = 1,
    out_features = 1
)

# optimizer

optimizer = torch.optim.SGD(
    model.parameters(),
    lr = 0.01

)

# Forward pass

for x_batch,y_batch in loader:

    #prediction

    predicted = model(x_batch)

    print("Before weight :", model.weight)


    # loss function

    loss_function = nn.MSELoss()
    loss = loss_function(predicted,y_batch)
    print("Loss : ",loss)

    #clear the old gradients

    print(optimizer.zero_grad())

    # backward pass

    loss.backward()

    print("Weight gradient : ",model.weight.grad)
    print("Bias gradient : ",model.bias.grad)


    #update weights 

    optimizer.step()

    print("After  : ", model.weight)

    print("After weight updation : ",model.weight)
    print("After bias updation : ",model.bias)


    break




Before weight : Parameter containing:
tensor([[0.3969]], requires_grad=True)
Loss :  tensor(922.3328, grad_fn=<MseLossBackward0>)
None
Weight gradient :  tensor([[-96.0359]])
Bias gradient :  tensor([-57.4896])
After  :  Parameter containing:
tensor([[1.3572]], requires_grad=True)
After weight updation :  Parameter containing:
tensor([[1.3572]], requires_grad=True)
After bias updation :  Parameter containing:
tensor([1.2348], requires_grad=True)


## Epoch

An epoch means:

One complete pass through the entire training dataset.

Let's use our current dataset:

x = [1, 2, 3, 4]
y = [20, 40, 60, 80]

We have 4 training samples.

Our DataLoader has:

batch_size = 2

So the DataLoader gives us:

Batch 1 → [1, 2]
Batch 2 → [3, 4]

When the model processes both batches, it has seen all 4 samples once.

That is 1 epoch.



Multiple epochs

If we train for:

epochs = 5

the model sees the entire dataset 5 times:

Epoch 1 → entire dataset
Epoch 2 → entire dataset
Epoch 3 → entire dataset
Epoch 4 → entire dataset
Epoch 5 → entire dataset

In [22]:
# import the libraries

import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch import nn as nn


# create the dataset 

class MyDataset(Dataset):

    # initlize the dataset

    def __init__(self):

        #input
        
        self.x = torch.tensor(
            [
                [1.0],
                [2.0],
                [3.0],
                [4.0]
            ]
        )

        #output

        self.y = torch.tensor(
            [
                [20.0],
                [40.0],
                [60.0],
                [80.0]
            ]
        )

    # len 

    def __len__(self):

        return len(self.x)

    # get the sample

    def __getitem__(self,index):

        return self.x[index],self.y[index]


# Dataset object

dataset = MyDataset()

# DataLoader 

loader = DataLoader(
        
        dataset,
        batch_size =2,
        shuffle = False
)


#Model

model = nn.Linear(

    in_features = 1,
    out_features = 1
)

# optimizer

optimizer = torch.optim.SGD(
    model.parameters(),
    lr = 0.01

)

#loss function

loss_function = nn.MSELoss()

for epoch in range(100):

    for x_batch,y_batch in loader:

        #Forward loss
        predicted = model(x_batch)

        #calcualte loss

        loss = loss_function(predicted,y_batch)

        #clear gradient
        optimizer.zero_grad()

        #backword loss
        loss.backward()

        #update the weights and bias
        optimizer.step()
    print("Epoch : ",epoch+1, "Loss : ",loss.item())    

print("weight : ",model.weight.item())
print("bis : ",model.bias.item())   

x = torch.tensor([3.0])

predicted = model(x)

print(predicted.item())

Epoch :  1 Loss :  4885.08544921875
Epoch :  2 Loss :  2319.17236328125
Epoch :  3 Loss :  1109.20703125
Epoch :  4 Loss :  536.1669311523438
Epoch :  5 Loss :  263.10687255859375
Epoch :  6 Loss :  131.87181091308594
Epoch :  7 Loss :  68.05220794677734
Epoch :  8 Loss :  36.521888732910156
Epoch :  9 Loss :  20.619403839111328
Epoch :  10 Loss :  12.388460159301758
Epoch :  11 Loss :  7.9938507080078125
Epoch :  12 Loss :  5.563277244567871
Epoch :  13 Loss :  4.167226791381836
Epoch :  14 Loss :  3.3339579105377197
Epoch :  15 Loss :  2.8176982402801514
Epoch :  16 Loss :  2.486347198486328
Epoch :  17 Loss :  2.2664172649383545
Epoch :  18 Loss :  2.1156036853790283
Epoch :  19 Loss :  2.0087122917175293
Epoch :  20 Loss :  1.930292010307312
Epoch :  21 Loss :  1.8705964088439941
Epoch :  22 Loss :  1.8234078884124756
Epoch :  23 Loss :  1.78463876247406
Epoch :  24 Loss :  1.7515950202941895
Epoch :  25 Loss :  1.722501277923584
Epoch :  26 Loss :  1.6961805820465088
Epoch :  27 L