## part 1


In [1]:
# import the troch library

import torch

import torch.nn as nn

## part 2

## -> simple Linear layer 

In [2]:
import torch
import torch.nn as nn

layer = nn.Linear(3,2)

x = torch.tensor([[10.,20.,30.]])

y = layer(x)

print(y)

tensor([[ 0.8546, 15.6804]], grad_fn=<AddmmBackward0>)


In [3]:
import torch 

import torch.nn as nn

layer = nn.Linear(3,2)

x = torch.tensor([
    [10.,20.,30.],
    [5.0,15.,25.]
])

output = layer(x)

print(output)

tensor([[-7.0866,  7.5655],
        [-6.1705,  6.0922]], grad_fn=<AddmmBackward0>)


In [10]:
# check the weights of the network

W = layer.weight

print("Weights : ",W)

# shape of the weight

print(W.shape)


# check the initial bias 

print(layer.bias)

print("shape of the bias : ",layer.bias.shape)

Weights :  Parameter containing:
tensor([[ 0.0884, -0.0061, -0.2655],
        [ 0.0727, -0.0369,  0.2588]], requires_grad=True)
torch.Size([2, 3])
Parameter containing:
tensor([ 0.1167, -0.1881], requires_grad=True)
shape of the bias :  torch.Size([2])


## Sequential layer

In [1]:
# import the torch module

import torch

import torch.nn as nn

x = torch.tensor([10.,20.,30.])

model = nn.Sequential(

    nn.Linear(3,4),
    nn.Linear(4,2)
)

# output 

output = model(x)

print(output)

tensor([ 5.0788, -6.9367], grad_fn=<ViewBackward0>)


## nn.Module

In [3]:
import torch 

import torch.nn as nn

class Mymodule(nn.Module):

    def __init__(self):

        super().__init__()

        self.layer1 = nn.Linear(3,5)

        self.relu = nn.ReLU()

        self.layer2 = nn.Linear(5,3)


    def forward(self,x):

        x = self.layer1(x)

        x = self.relu(x)

        x = self.layer2(x)

        return x



model = Mymodule()


x = torch.tensor([[1.0,2.0,3.0]])


output = model(x)



print("Model is : ")
print(model)


print("The input is : ", x)


print("The output is : ", output)

Model is : 
Mymodule(
  (layer1): Linear(in_features=3, out_features=5, bias=True)
  (relu): ReLU()
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)
The input is :  tensor([[1., 2., 3.]])
The output is :  tensor([[-0.1815,  0.0290, -0.0058]], grad_fn=<AddmmBackward0>)
