In [2]:
import torch

print(torch.__version__)

2.14.0+cpu


## 1 . Tensor

In [3]:
x = torch.tensor([1,2,3,4,5])

print(x)

tensor([1, 2, 3, 4, 5])


# 2 . Tensor Dimension


## -> Scaler

In [8]:
# scaler means single value

x = torch.tensor(5)

print(x)

x.shape

tensor(5)


torch.Size([])

## -> Vector

In [6]:
## single dimensional array 

vector = torch.tensor([1,2,3,4,5])

print(vector)

print(vector.shape)

tensor([1, 2, 3, 4, 5])
torch.Size([5])


## -> 2D array

In [10]:
## two dimensonal array 

matrix = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(matrix)

matrix.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

## Exercise one 

In [12]:
# create a 2d array and find it's size

import torch as t

mat = t.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(mat)

print()

print('The size of the tensor is : ',mat.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

The size of the tensor is :  torch.Size([3, 3])


## Different ways to create the Tensors

## -> torch.zeros()

In [ ]:
import torch

# syntax = zeros(rows,cols)

zero = torch.zeros(2,3)

print(zero)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


## -> torch.ones()


In [2]:
import torch as t

one_matrix = t.ones(3,3)

print(one_matrix)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## ->torch.arange()

In [3]:
import torch as t

range_tensor = t.arange(0,10)

print(range_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Random tensro

In [ ]:
import torch as t

# it takes values between the 0 & 1

# rand(rows,cols)

rand_arr = t.rand(2,3)

print(rand_arr)

tensor([[0.3933, 0.1658, 0.5905],
        [0.9726, 0.7154, 0.3341]])


# Datatypes


## -> int type

In [6]:
import torch as t

x = t.tensor([1,2,3,4,5])


print(x)


print()

print(x.dtype)

tensor([1, 2, 3, 4, 5])

torch.int64


## -> float type

In [9]:
import torch as t

x = t.tensor([1.0,2.0,3.1,7.4,4.3])

print(x)

print()

print("The type of the tensor x is : ",x.dtype)

tensor([1.0000, 2.0000, 3.1000, 7.4000, 4.3000])

The type of the tensor x is :  torch.float32


## Device cpu and Gpu

In [11]:
import torch as t


print(t.cuda.is_available())

False


In [16]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

cpu


## common pattern

In [15]:
import torch 

device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([1,2,3,4,5]).to(device)

print(x)

print(device)

tensor([1, 2, 3, 4, 5])
cpu
