# Tensor operations

In [1]:
import torch

print(torch.__version__)

2.14.0+cpu


# Arithmetic operations

## 1. Tensor Addition

In [2]:
# import the pytorch library

import torch as t

A = t.tensor([1,2,3,4,5])

B = t.tensor([1,3,2,5,6])

print("Tensor Addition : ", A+B)

Tensor Addition :  tensor([ 2,  5,  5,  9, 11])


## 2 . Tensor Subtaction

In [3]:
import torch as t

A = t.tensor([3,2,1])

B = t.tensor([1,3,4])

print("Tenosr Subraction : ",A-B)

Tenosr Subraction :  tensor([ 2, -1, -3])


## 3 . Tensor Multiplication

In [6]:
import torch as t

A = t.tensor([1,2,3])

B = t.tensor([3,2,3])

print("Tensor Multiplicaton : ",A*B)


# Note : It follows the element wise muliplication not matrix multiplication

Tensor Multiplicaton :  tensor([3, 4, 9])


## 4 . Tensor Division

In [7]:
import torch as t

A = t.tensor([2,4,6])

B = t.tensor([1,2,2])

print("Tenosr Division : ",A/B)

Tenosr Division :  tensor([2., 2., 3.])


# Scaler Operations

## add a constant 

In [9]:
# we can perform operations between a tensor and the scalar value (single ) 

import torch as t

x = t.tensor([1,2,3])

print(x+10)

tensor([11, 12, 13])


## Multiply with constant

In [10]:
import torch as t

x = t.tensor([1,2,3])

print(x*2)

tensor([2, 4, 6])


## Divide with constant

In [11]:
print(x/2)

tensor([0.5000, 1.0000, 1.5000])


## Important functions

## sum

In [15]:
x = t.tensor([1,2,3,4,5])

print(t.sum(x))

tensor(15)


## mean

In [14]:
print(t.mean(x.float()))

tensor(3.)


## maximum

In [16]:
print(t.max(x))

tensor(5)


## minimum

In [17]:
print(t.min(x))

tensor(1)


## Matrix Multiplication 

In [7]:
import torch

a = torch.tensor([
    [1,2,3],
    [4,5,6]
])

b = torch.tensor([
    [2,1],
    [7,5],
    [1,4]
])

print("Tensor Multiplication : ")

print(torch.matmul(a,b))

Tensor Multiplication : 
tensor([[19, 23],
        [49, 53]])
