# PANDAS MASTERY SERIES 

## DAY - 1 . Introduction to Pandas & Series


In [ ]:
# 1. What is Pandas?

# Pandas is a Python library used for working with structured (tabular) data.

# It helps you:

# Read CSV and Excel files
# Analyze datasets
# Clean missing or incorrect data
# Filter and sort data
# Perform statistical analysis
# Think of it like this:
# Library	Used For
# NumPy	Arrays and numerical computing
# Pandas	Tables and data analysis

# part - 2 (import statement)

In [6]:
import pandas as pd

print(pd.__version__)

3.0.5


## 2. Series Datatype

In [ ]:
# # A series is a one dimentional array

# It contains:

# Values
# Index labels

# Example:

# Index    Value

# 0        10
# 1        20
# 2        30
# # 3        40

## 3 . creating a series 

## From a list

In [8]:
import pandas as pd

arr = pd.Series([85,70,82,90,95])

print(arr)

# we see that the values are labeled 

0    85
1    70
2    82
3    90
4    95
dtype: int64


## From a Numpy array



In [9]:
import numpy as np

import pandas as pd

arr = np.random.randint(1,100,size = 10)

arr

array([89, 83, 61,  4, 25, 58, 54, 58,  2, 16])

In [10]:
# we convert the numpy array to the series

In [11]:
series = pd.Series(arr)

print(series)

0    89
1    83
2    61
3     4
4    25
5    58
6    54
7    58
8     2
9    16
dtype: int32


## From a dictonary

In [15]:
dict = {
    'maths':90,
    'science' : 85,
    'english' : 88,
    'social' : 70
}

# converting the dict to series

series = pd.Series(dict)

print(series)

# Here notice one thing , the key in the dictonary becomes the indexed labels       

maths      90
science    85
english    88
social     70
dtype: int64


## creating the custom index

In [16]:
# we can create the custom index 

custom = pd.Series(
    [90,85,88,70],
    index = ['maths','science','english','social']
)

print(custom)

maths      90
science    85
english    88
social     70
dtype: int64


## 4 . Accessing the elements

## By using position

In [21]:
import numpy as np
import pandas as pd

arr = np.random.randint(1,100,size = 9)

arr

new_arr = pd.Series(arr)

print(new_arr)

0    44
1    83
2     3
3    43
4    80
5    56
6    70
7    26
8    12
dtype: int32


In [22]:
# accessing by the using the position

print(new_arr[0])

44


In [23]:
print(new_arr[4])

80


## By using the label

In [24]:
dict = {
    'maths':90,
    'science' : 85,
    'english' : 88,
    'social' : 70
}

# converting the dict to series

series = pd.Series(dict)

print(series)
    

maths      90
science    85
english    88
social     70
dtype: int64


In [25]:
print(series['maths'])

90


## 5 . slicing

In [26]:
import numpy as np
import pandas as pd

array = np.random.randint(1,100,size =8)

print(array)

[68 86 61 33 89 14 59 36]


In [28]:
# converting it into the series dataframe
pd_array = pd.Series(array)

print(pd_array)

0    68
1    86
2    61
3    33
4    89
5    14
6    59
7    36
dtype: int32


In [31]:
# slicing

# syntax array(start:end:step)

print(pd_array[1:5:2])



1    86
3    33
dtype: int32


## 6 . Series attributes

In [32]:
# shape 

print(pd_array.shape)

(8,)


In [33]:
# type

print(pd_array.dtype)

int32


In [35]:
# index 

print(pd_array.index)

RangeIndex(start=0, stop=8, step=1)


In [36]:
# values

print(pd_array.values)

[68 86 61 33 89 14 59 36]


## 7 . mathematical operations


In [38]:

import numpy as np
import pandas as pd

num = np.random.randint(1,99 , size = 6)

print(num)

[39 27 96 98 52 60]


In [39]:
# converting it into the series 

number = pd.Series(num)

print(number)

0    39
1    27
2    96
3    98
4    52
5    60
dtype: int32


In [40]:
# Addtion , adding 5 to all values

print(number+5)

0     44
1     32
2    101
3    103
4     57
5     65
dtype: int32


In [41]:
# subtraction , subtract 5 from all values

print(number-5)

0    34
1    22
2    91
3    93
4    47
5    55
dtype: int32


In [42]:
# multiplication , multiply each value with 2

print(number *2)

0     78
1     54
2    192
3    196
4    104
5    120
dtype: int32


In [43]:
# Division , divide the each value with 2

print(number /2)

0    19.5
1    13.5
2    48.0
3    49.0
4    26.0
5    30.0
dtype: float64


## 8 . useful methods

In [45]:

import numpy as np
import pandas as pd

data = pd.Series(np.random.randint(1,50,size = 8))

print(data)

0    29
1    36
2    14
3     1
4     1
5    40
6    31
7    12
dtype: int32


In [56]:
# mean

print(data.mean())

20.5


In [57]:
# max 

print(data.max())

40


In [58]:
# min 

print(data.min())

1


In [59]:
# sum

print(data.sum())


164


In [60]:
# sd

print(data.std())

15.482709249814315


## 9 . filtering the values

In [52]:
data

0    29
1    36
2    14
3     1
4     1
5    40
6    31
7    12
dtype: int32

In [61]:
print(data[data>10])

# it displayes the values which are greater than 10

0    29
1    36
2    14
5    40
6    31
7    12
dtype: int32


## 10 . Handling missing values

In [63]:
import pandas as pd
import numpy as np
data = pd.Series([10,5,np.nan,15,np.nan,24,30,np.nan])

data

0    10.0
1     5.0
2     NaN
3    15.0
4     NaN
5    24.0
6    30.0
7     NaN
dtype: float64

In [67]:
#checking for missing values

In [66]:


print(data.isnull())

# it returns a boolean value

# False means , it contains values

# True means , it contain null values (there is no values)



0    False
1    False
2     True
3    False
4     True
5    False
6    False
7     True
dtype: bool


In [ ]:
# checking for non missing values

In [65]:
print(data.notnull())

# it returns a boolean value

# True = it contains values

# False  = it contain null value

0     True
1     True
2    False
3     True
4    False
5     True
6     True
7    False
dtype: bool
