## creating the numpy array

In [2]:

# import the numpy library

import numpy as np  

# creation of numpy array 

arr = np.array([1,2,3,4,5,6,7,8])

#display the output

print(arr)

[1 2 3 4 5 6 7 8]


# Type of array

In [4]:
# printing the type of array 

print(type(arr))

""" In the output {
  
    numpy = library name
    d - dimnesions
    n - n dimensions 
    array - collection of elements

    
    } 



<class 'numpy.ndarray'>


## 2. - create a integer array

In [5]:
# import library
import numpy as np

# array creation 

arr = np.array([1,2,3,4,5,6])

#output

print(arr)

[1 2 3 4 5 6]


## 3.zeros()

In [6]:
import numpy as np

zero = np.zeros(3) # creates the 1 d array with all elements as zeros , 3 means number of elements

print(zero)

[0. 0. 0.]


In [7]:
#creates the 2d array with all elements as zeros

zero_matrix = np.zeros((3,4))

zero_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 4.ones()

In [8]:
# creates the 1 d array with all elements as one

one = np.ones(3)
# 3 is the number of elements
one

array([1., 1., 1.])

In [9]:
# creates the 2 d array with all elements as one

one_matrix = np.ones((4,3))

# here rows = 4 and columns = 3
one_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 5. creating a empty array


In [20]:

empty = np.empty((2,2))

# creates a random merory values
empty

array([[1.63779371e-307, 1.26208501e-307],
       [5.89621022e-296,             nan]])

## 6.arange()

In [21]:
# this arange function generates a range of values

arr = np.arange(1,13)

# here it takes parametes(start,end) end is not included
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arr = np.arange(0,20,2)

# 2 is the step / jump
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
arr = np.arange(20)

arr

# observe one thing , end is not a part of any of these there

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 7.linspace()

In [28]:
# #creates a continous values between the start and the end 

# linspace(start,end,total number of values)

# may it include 0 and 1 as values

In [27]:
# implementing the linspace values

lin = np.linspace(0,1,5)

print(lin)

[0.   0.25 0.5  0.75 1.  ]


In [29]:
# example 2

lin2 = np.linspace(0,5,10)

lin2

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Attributes

In [38]:
# shape of the array

import numpy as np

arr = np.arange(1,21)

arr = arr.reshape(4,5)

print(arr)

print()

print("The shape of the matrix is : ", arr.shape)
print()
print("rows : 4 ")
print()
print("columns : 5")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

The shape of the matrix is :  (4, 5)

rows : 4 

columns : 5


## ndim

In [36]:
#dimensions

print(arr.ndim)

2


## size of the array



In [41]:
# size (total number of elements)

print(arr.size)

# arr contains the 20 elements

20


## dtype

In [42]:
## show the type of the elements in the array

print(arr.dtype)

int32
