# Linear Algebra for AI/ML

In [2]:
# Why should we learn Linear Algebra?

# Almost everything in AI is represented as numbers.

# Images → Matrix of pixel values
# Text → Matrix of embeddings
# # Audio → Matrix of signals
# Dataset → Matrix
# Neural Network Weights → Matrix
# Transformer Attention → Matrix

## 1. What is a Vector?


In [4]:
# vector is a array 

import numpy as np

arr = np.array([1,2,3])  # arr is vector 

print(arr)

[1 2 3]


In [6]:
# dimension of the vector

print(arr.ndim)

1


## 2. What is a Matrix?


In [8]:
# A matrix is a 2d array 

matrix = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(matrix)

[[1 2 3]
 [4 5 6]]


## shape of the matrix


In [10]:
print(matrix.shape)

(2, 3)


## 3. Dot Product


In [12]:
# creating the two practice arrays 


a = np.array([1,2,3])
b = np.array([4,5,6])

print(a)
print(b)

[1 2 3]
[4 5 6]


In [13]:
# dot product of the two arrays

np.dot(a,b)

# 1×4 = 4

# 2×5 =10

# 3×6 =18

# Total =32

#a·b

# =

# Σ(ai × bi)

np.int32(32)

## 4. Matrix Multiplication


In [15]:
# matrix A(2,3) 

A = np.array([
    [1,2,3],
    [4,5,6]
])

# matrix B(3,2)
B = np.array([
    [7,8],
    [9,10],
    [11,12]
])

print(A)

print()
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]


In [16]:
# one way

A @ B  # matrix multiplication

array([[ 58,  64],
       [139, 154]])

In [17]:
# anoter way 

np.matmul(A,B)


# (m × n)

# ×

# (n × p)

# ↓

# (m × p)

array([[ 58,  64],
       [139, 154]])

## 5. Transpose


In [21]:
# swaps the rows and columns

A = np.array([
    [1,2,3],
    [4,5,6]
])

print("Before Transpose")
print()
print(A)
print()
print("After Transpose")
print()

print(A.T)



Before Transpose

[[1 2 3]
 [4 5 6]]

After Transpose

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Computing similarities
# Matrix multiplication
# Linear regression
# Neural network backpropagation

## 6. Identity Matrix


In [29]:
# Identity matrix is like the number 1 for matrices

np.eye(3)  #(3 means dimension)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# A × I = A

A = np.arange(1,10)

A = A.reshape(3,3)

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# identity matrix

I  = np.eye(3)

A@I

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## 7. Determinant


In [ ]:
# The determinant tells us important properties about a matrix, such as whether it is invertible.

# For a 2×2 matrix:

# A=[
# [a,c],
# [b,d]
# ]

# The determinant is:

# ad−bc

In [37]:
A = np.array([
    [9,2],
    [3,4]
])

A

array([[9, 2],
       [3, 4]])

In [38]:
det = np.linalg.det(A)

print(det)

30.000000000000014


In [39]:
# Interpretation
# Determinant ≠ 0 → Matrix has an inverse.
# # Determinant = 0 → Matrix is singular (cannot be inverted).

## 8 . inverse

In [42]:
A = np.array([
    [2,1],
    [5,3]
])

A_inv = np.linalg.inv(A)

print(A_inv)

[[ 3. -1.]
 [-5.  2.]]


## 9. Eigenvalues & Eigenvectors

In [ ]:
# This is one of the most important ideas in linear algebra.

# Imagine stretching an object.

# Most directions change.

# Some special directions only get scaled, not rotated.

# Those special directions are eigenvectors.

# The amount they are stretched is the eigenvalue.

In [44]:
A = np.array([
    [4,2],
    [1,3]
])

values, vectors = np.linalg.eig(A)

print(values)
print()
print(vectors)

[5. 2.]

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
# You don't need to derive them mathematically right now. What's important is understanding where they're used.

# Applications
# PCA (Principal Component Analysis)
# Face Recognition
# Google PageRank
# Image Compression
# Data Dimensionality Reduction