# Eligen values and Eligen vectors

In [ ]:
# Suppose you stretch a rubber sheet.

# Most arrows drawn on it will change both:

# Length
# Direction

# But a few special arrows only change their length, not their direction.

# Those special arrows are called Eigenvectors.

# The amount they stretch is called the Eigenvalue.

# Mathematical Definition

# If

# Ax=λx

# where

# A → matrix
# x → eigenvector
# λ → eigenvalue

# then x is an eigenvector of A.?

In [4]:
import numpy as np

A = np.array([
    [4,2],
    [1,3]
])

A

array([[4, 2],
       [1, 3]])

In [5]:
# working on the eligen values and vectors

values,vectors = np.linalg.eig(A)

print(values)

print(vectors)

[5.+0.j 2.+0.j]
[[ 0.89442719+0.j -0.70710678+0.j]
 [ 0.4472136 +0.j  0.70710678+0.j]]


In [6]:
A = np.array([
    [4,2],
    [1,3]
])

values, vectors = np.linalg.eig(A)

v = vectors[:,0]

print(A @ v)
print(values[0] * v)

[4.47213595+0.j 2.23606798+0.j]
[4.47213595+0.j 2.23606798+0.j]


## Mini challenge

In [8]:
import numpy as np

arr = np.array([
    [2,1],
    [1,2]
])

arr

array([[2, 1],
       [1, 2]])

In [10]:
# transpose

print(np.transpose(arr))

[[2 1]
 [1 2]]


In [11]:
# anther method for transpose

print(arr.T)

[[2 1]
 [1 2]]


In [12]:
#matrix multiplication

a = np.arange(4,8)

a = a.reshape(2,2)

print(a)

[[4 5]
 [6 7]]


In [13]:
# matrix multiplication

print(arr@a)

[[14 17]
 [16 19]]


In [15]:
# determinent of matrix arr

print(np.linalg.det(arr))

2.9999999999999996


In [16]:
# inverse of the matrix arr

print(np.linalg.inv(arr))


[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


In [18]:
# identity matrix

print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
