# MINI PROJECT


## STUDENT GRADE ANALYZER (NUMPY ONLY)

# GOAL

In [2]:
# Build a student grade analyzer using numpy only

## REQUIREMENTS

In [ ]:
we have 100 students

Each student have subject marks between (35,100)

-> Each row is one student

-> Each column is one subject 


          Math  Physics  Chemistry  English  AI
Student1   75      82        91        64     89
Student2   61      55        74        90     80
Student3   95      92        97        88     94
...

## Task 1 - GENERATE THE DATASET

## import the libraries


In [8]:
import numpy as np
import random

data_set = np.random.randint(35,101,size=(100,5))

data_set

array([[ 45,  46,  88,  56,  47],
       [ 75,  77,  59,  97,  38],
       [ 70,  52,  85,  60,  61],
       [ 38,  79,  66,  72,  44],
       [ 87,  70,  49,  67,  59],
       [ 41, 100,  39,  55,  59],
       [ 74,  96,  76,  44,  78],
       [ 53, 100,  36,  70,  79],
       [ 62,  96,  90,  97,  57],
       [ 55,  73,  88,  59,  90],
       [ 64,  36,  95,  49,  53],
       [ 69,  71,  38,  35,  80],
       [ 42,  72,  91,  74,  49],
       [ 84,  45,  99,  59,  97],
       [ 35,  94,  72,  60,  65],
       [ 86,  45,  80,  51,  70],
       [ 69,  81,  54,  68,  44],
       [ 74,  46,  62,  57,  61],
       [ 67,  58,  55,  54,  45],
       [ 41,  78,  61,  74,  66],
       [ 51,  38,  84,  92,  41],
       [ 38,  59,  93,  62,  68],
       [ 49,  48,  60,  74,  88],
       [ 58,  93,  57,  73,  96],
       [ 68,  94,  57,  40,  82],
       [ 84,  54,  89,  60,  73],
       [ 68,  40,  97,  63,  78],
       [ 47,  61,  89,  75,  70],
       [ 93,  91,  91,  59,  63],
       [ 55,  

# Task -2 Basic information

## shape of the dataset

In [9]:
data_set.shape

(100, 5)

## Dimensions

In [10]:
data_set.ndim

2

## Type of the data_set

In [11]:
data_set.dtype

dtype('int32')

## Total values

In [12]:
data_set.size

500

# Task - 3 student average

In [26]:
# Average of each student

average =  np.mean(data_set,axis=1)

average

array([56.4, 69.2, 65.6, 59.8, 66.4, 58.8, 73.6, 67.6, 80.4, 73. , 59.4,
       58.6, 65.6, 76.8, 65.2, 66.4, 63.2, 60. , 55.8, 64. , 61.2, 64. ,
       63.8, 75.4, 68.2, 72. , 69.2, 68.4, 79.4, 66.6, 62.6, 69.4, 76.4,
       64.4, 58.4, 67. , 72.4, 64.6, 66.6, 54. , 60.8, 74. , 85.4, 77.8,
       57. , 78. , 75.8, 64.6, 76. , 49.4, 71. , 82.6, 63. , 69.6, 67.4,
       55. , 77.8, 81.2, 77.6, 58.2, 61.4, 73.4, 71.4, 70. , 61. , 65.6,
       67. , 62.8, 75.4, 63.4, 73.2, 68.6, 78.2, 67.8, 78.6, 62.2, 75. ,
       82.6, 57.4, 62.2, 64. , 51. , 72.6, 58.6, 71.2, 67.8, 71.8, 66.6,
       59.8, 62. , 44.6, 71. , 56.6, 66.2, 64.4, 60. , 54. , 75.2, 60.8,
       70. ])

# Task - 4 subject wise average

In [27]:
sub_avg = np.mean(data_set,axis = 0)

sub_avg

array([66.61, 64.96, 69.93, 67.34, 66.03])

# Task - 5 Highest scorer

In [37]:

top = np.sum(data_set,axis = 1)


print("student : ", np.argmax(top) +1)

print("marks : ",np.max(top))

student :  43
marks :  427


# Task - 6 Lowest scorer

In [38]:
low = np.sum(data_set,axis = 1)

low

array([282, 346, 328, 299, 332, 294, 368, 338, 402, 365, 297, 293, 328,
       384, 326, 332, 316, 300, 279, 320, 306, 320, 319, 377, 341, 360,
       346, 342, 397, 333, 313, 347, 382, 322, 292, 335, 362, 323, 333,
       270, 304, 370, 427, 389, 285, 390, 379, 323, 380, 247, 355, 413,
       315, 348, 337, 275, 389, 406, 388, 291, 307, 367, 357, 350, 305,
       328, 335, 314, 377, 317, 366, 343, 391, 339, 393, 311, 375, 413,
       287, 311, 320, 255, 363, 293, 356, 339, 359, 333, 299, 310, 223,
       355, 283, 331, 322, 300, 270, 376, 304, 350])

In [39]:
# finding the low scorer

print("student : ", np.argmin(low))

print("marks : ", np.min(low))

student :  90
marks :  223


# Task - 7 find the top scorer in each subject

In [41]:

sub_top = np.max(data_set,axis = 0)

sub_top

array([ 99, 100, 100, 100, 100])

# Task - 8 Failed students

In [49]:
# failed students 

rows , cols = np.where(data_set<40)

rows

array([ 1,  3,  5,  7, 10, 11, 11, 14, 20, 21, 30, 33, 34, 38, 40, 44, 49,
       49, 53, 54, 55, 56, 59, 60, 71, 75, 79, 81, 81, 85, 89, 90, 90, 90,
       91, 92, 94, 96, 97])

# Task 9  Finding the Grade

In [69]:

# finding the average

for x,avg in enumerate(average):

    if(avg>90):
        print(f"student {x+1} -> A")
    elif(avg > 80):
        print(f"student {x+1} -> B")

    elif(avg > 70):
        print(f"student {x+1} -> C")
    elif(avg > 60):
        print(f"student {x+1} -> D")
    elif(avg < 60):
        print(f"student {x+1} -> F")

student 1 -> F
student 2 -> D
student 3 -> D
student 4 -> F
student 5 -> D
student 6 -> F
student 7 -> C
student 8 -> D
student 9 -> B
student 10 -> C
student 11 -> F
student 12 -> F
student 13 -> D
student 14 -> C
student 15 -> D
student 16 -> D
student 17 -> D
student 19 -> F
student 20 -> D
student 21 -> D
student 22 -> D
student 23 -> D
student 24 -> C
student 25 -> D
student 26 -> C
student 27 -> D
student 28 -> D
student 29 -> C
student 30 -> D
student 31 -> D
student 32 -> D
student 33 -> C
student 34 -> D
student 35 -> F
student 36 -> D
student 37 -> C
student 38 -> D
student 39 -> D
student 40 -> F
student 41 -> D
student 42 -> C
student 43 -> B
student 44 -> C
student 45 -> F
student 46 -> C
student 47 -> C
student 48 -> D
student 49 -> C
student 50 -> F
student 51 -> C
student 52 -> B
student 53 -> D
student 54 -> D
student 55 -> D
student 56 -> F
student 57 -> C
student 58 -> B
student 59 -> C
student 60 -> F
student 61 -> D
student 62 -> C
student 63 -> C
student 64 -> D
s

In [ ]:
🏆 Bonus Challenges

If you finish early:

Find top 10 students.
Rank all students.
Count how many students got each grade.
Find students who scored above 90 in all subjects.
Find students who scored above the class average in every subject.
Display a simple report card for any student.