# Random series 

# PART 1

In [1]:
# The random module generates the values for simulations ,machine learning and testing

## Generating a float value


In [3]:
import numpy as np

float_val = np.random.rand()

print(float_val)

0.03786813548844492


## Generating multiple float values



In [5]:
arr = np.random.rand(4)

# here we are generating 4 float vlaues
print(arr)

[0.13792827 0.40657439 0.12092539 0.55451643]


## Generaing a random matrix

In [6]:
matrix = np.random.rand(3,4)

print(matrix)

[[0.49490313 0.95407341 0.39541675 0.49672036]
 [0.60807442 0.77557019 0.65862258 0.35654405]
 [0.36660753 0.93403725 0.08493306 0.28937383]]


# PART 2 

## Generating integer values

In [12]:
import numpy as np

int_val = np.random.randint(1,10,)

# start is inclusive

# end is exclusive

# size = number of elements 

print(int_val)

6


## Generating multiple integer values


In [15]:
arr = np.random.randint(1,100,size=10)

# we are generating 10 values 
print(arr)

[15 14  5  5 30 50 70  6 76 34]


In [21]:
# Generating integer matrix

matrix = np.random.randint(1,100,size=(3,4))

print(matrix)

[[68 25 84 52]
 [24 18 50 35]
 [23 34 88 87]]


# PART 3

## Random seed



In [4]:
import numpy as np
np.random.seed(42)

arr = np.random.randint(1,100,size = (10,5))

print(arr)

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]
 [58 22 89 49 91]
 [59 42 92 60 80]
 [15 62 62 47 62]
 [51 55 64  3 51]
 [ 7 21 73 39 18]]
